package com.hydrozoa.pokemon.model;

/**
 * @author hydrozoa
 */
public enum TERRAIN {
	
	GRASS_1,
	GRASS_2,
	INDOOR_TILES,
	INDOOR_TILES_SHADOW,
	WALL_BOTTOM,
	WALL_TOP,
	
	BROWN_PATH,
	BROWN_PATH_GRASS_NORTH,
	BROWN_PATH_GRASS_EAST,
	BROWN_PATH_GRASS_SOUTH,
	BROWN_PATH_GRASS_WEST,
	BROWN_PATH_GRASS_NORTHEAST,
	BROWN_PATH_GRASS_NORTHWEST,
	BROWN_PATH_GRASS_SOUTHEAST,
	BROWN_PATH_GRASS_SOUTHWEST,
	;

}
